### ISSUE TITLE
Armv7 Support

### ISSUE THREAD

**Issue by ChristopherJMiller** [hotio/cloudflareddns#25]
I noticed in the github actions that [armv7 build support is referenced](https://github.com/hotio/cloudflareddns/blob/797841c5344fa09d7dae5f7890698e86105a55a7/.github/workflows/build.yml#LL249C1-L249C1) but no Dockerfile exists to facilitate the build. Is armv7 support coming in the future?

**Comment by mrhotio** [comment]
No, it was there in the past
