### ISSUE TITLE
Ability to exit container after update (bypass/disable INTERVAL)

### ISSUE THREAD

**Issue by afonsoc12** [hotio/cloudflareddns#27]
Hi,

Would it be possible to have a way to bypass the `INTERVAL` sleep setting and allowing the container to finish successfully upon update?
My use case is to be able to run this container as a k8s CronJob, which is already scheduled every 15 mins. Therefore, the container would need to exit after updating.

I was thinking about setting Interval to 0 or -1, which would disable sleeping and exit with 0

**Comment by mrhotio** [comment]
yeah, should be doable
