### ISSUE TITLE
Use one.one.one.one

### ISSUE THREAD

**Issue by NLZ** [hotio/cloudflareddns#28]
https://github.com/hotio/cloudflareddns/blob/b95fa4eee21e0a47a8cfebb24b715df5ba9d7458/root/app/cloudflare-ddns.sh#L129-L130

Similarly to how the other dig methods are using dns resolver hostnames, wouldn't it be better to use `one.one.one.one` for Cloudflare?
Like this:
```sh
 [[ ${CHECK_IPV4} == "true" ]] && newipv4=$(dig -4 TXT +short whoami.cloudflare @one.one.one.one ch 2>/dev/null | tr -d '"') 
 [[ ${CHECK_IPV6} == "true" ]] && newipv6=$(dig -6 TXT +short whoami.cloudflare @one.one.one.one ch 2>/dev/null | tr -d '"') 
```

**Comment by mrhotio** [comment]
Why?
